CREATE OR REPLACE FUNCTION GET_PERIOD_ID (
    IN_INCREMENT_DATE IN DATE
) RETURN VARCHAR2
IS
    CURSOR C1
    IS
    SELECT PERIOD_ID 
    FROM GL_PERIODS 
    WHERE IN_INCREMENT_DATE BETWEEN START_DATE AND END_DATE;
    L_VAR VARCHAR2(20);
BEGIN
    OPEN C1;
        FETCH C1 INTO L_VAR;
    CLOSE C1;
    RETURN L_VAR;
EXCEPTION
    WHEN OTHERS THEN
    RETURN '0';
END;
/
